### ISSUE TITLE
FilePersistentCacheStore attempting to read metadata from non-existent directory

### ISSUE THREAD

**Issue by cpmcdaniel** [httpcache4j/httpcache4j#45]
I'm not sure, but it looks like you need to call Files.exists on the directory before trying to create the new DirectoryStream:

```
2016-01-06 09:13:08.037:WARN:oejs.HttpChannel:qtp1407083101-23: http://www.apache.org/
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /var/tmp/proxy-cache/files/44/449550d1903c30772e008db3acd3de7d
	at org.codehaus.httpcache4j.cache.FilePersistentCacheStorage.getMetadata(FilePersistentCacheStorage.java:225)
	at org.codehaus.httpcache4j.cache.FilePersistentCacheStorage.getItem(FilePersistentCacheStorage.java:146)
	at org.codehaus.httpcache4j.cache.FilePersistentCacheStorage.get(FilePersistentCacheStorage.java:137)
	at org.codehaus.httpcache4j.cache.HTTPCache.getFromStorage(HTTPCache.java:121)
	at org.codehaus.httpcache4j.cache.HTTPCache.doRequest(HTTPCache.java:113)
	at org.codehaus.httpcache4j.cache.HTTPCache.execute(HTTPCache.java:88)
	at org.codehaus.httpcache4j.cache.HTTPCache.execute(HTTPCache.java:66)
```

**Comment by hamnis** [comment]
PR?

**Comment by cpmcdaniel** [comment]
https://github.com/httpcache4j/httpcache4j/pull/47

**Comment by hamnis** [comment]
Merged. Thanks.
